apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgASp0iLba/+DqbIYX0FnEfVcDV2Td2kY1ZPBK05F7tPqPSazRGzTBUYDZ2crvwz6jOyjHvB2dLJB/ALqAolOoMKmpipkXwqGEJwKwSKhd1wyG3Pa+F4G5n0Xg7dnIY3Blb05QWpX2NJSbYXufwJUpsMCa2WFxIbNbZsWSk/CL/KfByVMIaJXmd2M4IdBsfsx+s2mHEYv+8oWVMcgLH+S52pteObhcmL2O5phBPdfg7+nyUIGBIRueuer741s/tH83zRIUii+urqILlf4i2p/Rowd0iTb/P9pzORwLt9lpv3skUPIYJaoFUEA1ab8vZcgk6YrW9Q+gkptU5kUWZ+k2db27LSfEHYRt5OtEjF1Ue6Fh9gnLpxSs/yWcPWrn9YNHJunPM6q1EhIm0sTGTo1byRzqXJrj2U2wp6rvo0JRAjQLi+YsY+xCPu1Q7ydxQoXzD7d6DF29NJueqnSm8KohucDf4Kab8WUT8TQLXRsfuR1t+E3888WnkjWU/W7pibDLfdfKms49Ht7xSc4oE2hB1GHKEFRR+8KHEApSc7Or9PXgLASaYcEnRkkDgzFpBBUbGOyoM5qAd80NMrOGRwI2UJjWec4gFGvzMOCKr5njpd/MLIz/AoPoHoWxC6d1op4AF1lVx3/86AOEU7NZt/YPFLrQwRIYDJEkZY9WlR0lbtAx2dYZp9Vr0rQvmlCvF3JqKoKm+14Za+e5qqOkwhbw9Xi+o93Rb/ICVtLVIHiDUKhmdRclmjBTz1O+nICnAYClFiQra2rrs7xtTNIM3iVMJDs/j5nqimJZIhii0f8alzMMqToRrXpJqEoVwpJDQNATuwGLyKKhQieJ65upIj2GvgvqoqF1U2EHiVelFUZ5ZrrRJmqBWG8pprJqHjQZfdGjDTXVun4zOP6iirWUWYPeKOUFts5qZRLw==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

