apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCe8RVJMn8GdXj6SL+sNFFdi4UJW5UYS4I937drAtGfJO0oPQFMHVNSRV0+pj60sB7X+lvQedjfFtIHuyZqsXgojCeXfbQffT4iOyon3wDw4JXFm+hjttIH7En6nGh/VogKtrS4jeiNXTFIQUV0YqqLIanlFPlxhBTq+ewkNgkvzz6rx0T/dW2yRUK7EH+Uko0Nkvf3UeOpIcr9FfU1lnQtEkkvUuu8+pnkmv32PjmdRAsWgfL9VKx3EAECyqCcrTSgvRMdd6xBXjoE0jYij92XcYKkO1ah4q1djt+4CJGbAPZxPUplpIBe7250owTOK+zaDUQMwOiQCmrCSbP+L96aU84fxpsFCTZWCFW27+fCMRAjC1KlzqyBqF4nUcd7CekXHyLTpH9pesnTGLMdiQ9MWUkKv4OyY+PLgKEJU9P4UAdEtLMG+hU4C6YC5gfKT8hOnwr5useFtOGxPsyAny8F5EgFZbnyq47XLQxPT0wyIJJSlf4LsSjuEzuCm3xZBJBts5Wt52z8ox2tooT6fVEsZ0sbRPWjkc/D7mfUs21Y07KBvusKIkXE4dsTk6a0myQlYuiwaecyTzQ4YbAzIRSQpcYop/GHUz+eiIYeE9iXF9TJ6jnws9c1wVMnhPSBe91AEKaQ4966UTYKLHIg/w/m56xb5j6ULgya6KDT5rmBQ1rxegVvqmdtadWUG2xFpTMoyv2INxvQPEKwBJ65aqF0amsL4RVCD9bDT1x8iZXLGl2gQgRWvUl1
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

