apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBYf8iaTKVSqhZx48NVq4yl1ZiMS6kBxb/5bZVbEEGS34ARXU8m3z6bB9i17Y63R4qehSvZD/0O2InBzkJs9RSr2Jcja/kDT9tmnAhbFbSXa7UfKFip5tehU1XgqyLn5Lx512Rx3xgp2bM/XGQazUKAHMJf0tiODi8Ul2FB7JKENMLqmzVrmXwAO1oMG3WYiFr9vcQalxxCF1umA2ZwHeVEttahU07J3opXY6FTuDTzQDfZWpUCQ+bUK5YaPSMlAZlPUe4rDDxdGZO4aOSUEBofNuwgAaIuKyy+l9oEM/nVIQqQ2XdGw/ke1aZQNIi7M9RO5pwM6OgbS14QKqcGbtgtg3mIP4cOvKWd0ZXlhH2qY/VtA85xWMbWNXvpGSdOHBkpmQRO22iH3blzX4Y8hhGrGJCYX/4qN/B6UMLDsqKonpdafN03P+mtkvL4ZkxrT6lr5Ut1DNjM4O/5mOk3NmtytNbhVYuSCJbjvgrye4JJFQwHqRTzfSRYLdf8h0sBaYe3sa9fN29PmoGjnK+3IEbzpPcXpjIJ365ferAgUFjCTVl7Wj9n/l1CcVwr+yRV+9o6wdJlV6ZRvACHGDsHEqc0VGufS7FCNitEY7vgRa1e9piWh77CyixuI9FTJHNvHj4pWk10MYknjUHa+yShVxx/zmmo4IbMTadPIE9bZuXLTVWOvbD+2r74Cg60UZOZHCWZq76HZwA7oZGSZHM4HdWtmERBLEUkOr3EXPu4h0Ahzuu2veTp+HEZ
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

