apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCBRHIChUcUfQNqUFJdul+a/xZELmPenq8OveDQQAXj+Pp8TTSI7PjKQxREXTd4Wn40MtRKeb9Pz80314RLi5Pp9vFlUMLckNqCAfmtEp5BQOH0wS/+c2qJ2GbrbNTXq57VkQ7MBWgCIw+JIfhRqZU3gpDK4l1EAdIbAHbdodrQ0GXdIkjhDCYeKBi3Snf0rwi6druiJDgwDpDJYDS5eCrYLF0V82ep+pTIpe4wWbA1HrFwzWrNHH05ACq5i0eGZSZVyuWlA6KqdUSFfDxexYGTiMn1RTZBQQMNyYJkHJuXyIEXdVdGE2AwXNhZHIVR/ozucVp/+G8cS+e6ob/rDXP1n27dqlfsJi/Kw5ZrC9oIDGVTOnd1HQ0hN/CzCJYr2793jCjA2zKElnXtRRZoJajQbw98gEgSla2MfkIzO/6dxUBKpqbOf+3QZe1IMRFJ02flwJeHXd2E05Aa4iljE8F9yh2eCZWOaeey/0AZU0K2aZJ8Qw1t9L/7n5xlzIfrJ4qz9K04Y+dQtj16vstZvMx5j+9YrNjYgtblO4x0OU49yw9dYZRH9LaM5zKIQapcikkEO3AAR83IwYr1tosStwKXXkLCmiQq4ZrVTpcUmO85V3VJ4dXaLVVaakhTKIqC9eH6K7a1Sq6W5dZcwlhedhwPC6pos+7si0kTjpmY0BBMCROPSluqYKgpCVL3jn67HCVHIJ6SvYuRr4sFIjTjkrr1Ksf697WERd2qVeVVO0a5D4GTkKsBpkc4
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

